Urf 6 refactor all
utaipei-sa/reserve.utsa pull request #5
Opened 2024-06-26 09:27 UTC by Jeff92316046

refactor all page to component and pull out api
###  page to component

- [X] from
- [ ] timetable 
- [ ] verify
- [ ] home

### pull out api

- [ ] reserve(post,put,del,get)
- [ ] items 
- [ ] spaces
- [ ] item_available_time
- [ ] space_available_time
- [ ] verify

2024-06-26 13:37 UTC, nickchengtw requested changes

2024-06-26 13:37 UTC, nickchengtw commented on src/components/form/ItemShower.vue
Shower很像是淋浴的意思?
要不要改成ItemDisplay或ItemTable

2024-06-26 13:37 UTC, nickchengtw commented on src/components/form/SpaceShower.vue
Shower很像是淋浴的意思?
要不要改成SpaceDisplay或SpaceTable

2024-06-26 13:37 UTC, nickchengtw commented on src/components/form/SubmitDialog.vue
> +            <v-row v-if="wh.width.value >= 960 && submit_data.item_data.length != 0">
這邊能不能改用ItemShower元件代替?

2024-06-26 13:37 UTC, nickchengtw commented on src/components/form/SubmitDialog.vue
> +            <v-row v-if="wh.width.value >= 960 && submit_data.space_data.length != 0">
這邊能不能改用SpaceShower元件代替?

2024-06-26 13:45 UTC, nickchengtw requested changes

2024-06-26 13:45 UTC, nickchengtw commented on src/components/form/ItemShower.vue
這個元件要不要改用vuetify的table元件做?
https://vuetifyjs.com/en/components/tables/

2024-06-26 13:45 UTC, nickchengtw commented on src/components/form/SpaceShower.vue
這個元件要不要改用vuetify的table元件做?
https://vuetifyjs.com/en/components/tables/

2024-06-26 14:01 UTC, Jeff92316046 commented on src/components/form/ItemShower.vue
待會改成Itemdisplay

可以，但感覺可以往後擺，再另外開個issue跟branch之類的
當時沒想到

2024-06-26 14:03 UTC, Jeff92316046 commented on src/components/form/SubmitDialog.vue
> +            <v-row v-if="wh.width.value >= 960 && submit_data.item_data.length != 0">
待會改

2024-06-26 14:03 UTC, Jeff92316046 commented on src/components/form/SubmitDialog.vue
> +            <v-row v-if="wh.width.value >= 960 && submit_data.space_data.length != 0">
待會改

2024-06-27 05:21 UTC, Jeff92316046 commented on src/components/form/SubmitDialog.vue
> +            <v-row v-if="wh.width.value >= 960 && submit_data.item_data.length != 0">
我後來想想這個跟上面的table一起改好了不然不太方便

2024-06-27 11:39 UTC, Jeff92316046 commented
我用timetable試了一下vuetify的table元件
可以看一下

2024-06-28 04:22 UTC, Jeff92316046 commented on src/components/form/ItemShower.vue
![擷取](https://github.com/utaipei-sa/reserve.utsa/assets/83210887/29522887-a28b-4ddc-887b-955d84af90f6)
如果螢幕太小，會變這樣
如果要用的話可能要用響應式一半用成這樣
![擷取1](https://github.com/utaipei-sa/reserve.utsa/assets/83210887/174ae8bb-1cc5-49f7-8f5d-26199fcd4eee)

2024-06-28 06:57 UTC, Jeff92316046 commented on src/components/form/ItemShower.vue
https://github.com/utaipei-sa/reserve.utsa/pull/5/commits/8968faae58efceefc54298935604a07397683e1c
這個看一下，覺得如何

2024-06-28 07:22 UTC, nickchengtw commented on src/components/form/ItemDisplay.vue
> +  <!-- <v-row v-if="wh.width.value >= width_rwd && item_data.length != 0">
這些註解如果不用就可以刪掉了?

2024-06-28 07:22 UTC, nickchengtw commented on src/components/form/SpaceDisplay.vue
> +  <!-- <v-row v-if="wh.width.value >= 600 && space_data.length != 0">
這些註解如果不用就可以刪掉了?

2024-06-28 07:22 UTC, Jeff92316046 commented on src/components/form/ItemDisplay.vue
> +  <!-- <v-row v-if="wh.width.value >= width_rwd && item_data.length != 0">
你看一下那個UI沒問題就刪了

2024-06-28 07:25 UTC, nickchengtw commented on src/components/form/ItemDisplay.vue
> +  <!-- <v-row v-if="wh.width.value >= width_rwd && item_data.length != 0">
我把ItemDisplay的issue close了
那個UI是沒問題的

2024-06-28 07:29 UTC, nickchengtw commented on src/components/basic/DatePicker.vue
> +const date_temp = defineModel('date_temp')
應該有比date_temp更明確的名稱?
ex: selected_date, input_date

2024-06-28 07:30 UTC, nickchengtw commented on src/components/basic/DatePicker.vue
> +const menu_open = ref(false)
boolean很像通常會在前面加is或has來幫助區分?
ex: is_menu_open

2024-06-28 07:32 UTC, nickchengtw commented on src/components/basic/DatePicker.vue
> +  setTimeout(() => {
為什麼需要讓datepicker延時關閉?

2024-06-28 07:38 UTC, Jeff92316046 commented on src/components/form/ItemDisplay.vue
> +  <!-- <v-row v-if="wh.width.value >= width_rwd && item_data.length != 0">
https://github.com/utaipei-sa/reserve.utsa/pull/5/commits/320f2becfbfcb81d5243704c51b26b616832f588

2024-06-28 07:38 UTC, Jeff92316046 commented on src/components/form/SpaceDisplay.vue
> +  <!-- <v-row v-if="wh.width.value >= 600 && space_data.length != 0">
https://github.com/utaipei-sa/reserve.utsa/pull/5/commits/320f2becfbfcb81d5243704c51b26b616832f588

2024-06-28 07:42 UTC, Jeff92316046 commented on src/components/basic/DatePicker.vue
> +  setTimeout(() => {
讓那個datepicker關的比較絲滑一點
可以把那個拔掉試試看

2024-06-28 07:47 UTC, nickchengtw commented on src/components/basic/DatePicker.vue
> +  setTimeout(() => {
我自己覺得還好
如果你喜歡這個效果就把他留著

2024-06-28 07:48 UTC, nickchengtw commented on src/components/form/SubmitDialog.vue
> +            <!-- <v-row v-if="wh.width.value >= 960 && submit_data.item_data.length != 0">
不用因該就可以刪掉了

2024-06-28 07:48 UTC, nickchengtw commented on src/components/form/SubmitDialog.vue
> +            <!-- <v-row v-if="wh.width.value >= 960 && submit_data.space_data.length != 0">
不用因該就可以刪掉了

2024-06-28 07:52 UTC, Jeff92316046 commented on src/components/form/SubmitDialog.vue
> +            <!-- <v-row v-if="wh.width.value >= 960 && submit_data.space_data.length != 0">
https://github.com/utaipei-sa/reserve.utsa/pull/5/commits/a7fde8062e99df20f513ac81bb855ccebcf015b3

2024-06-28 07:52 UTC, Jeff92316046 commented on src/components/form/SubmitDialog.vue
> +            <!-- <v-row v-if="wh.width.value >= 960 && submit_data.item_data.length != 0">
https://github.com/utaipei-sa/reserve.utsa/pull/5/commits/a7fde8062e99df20f513ac81bb855ccebcf015b3

2024-06-28 07:52 UTC, Jeff92316046 commented on src/components/basic/DatePicker.vue
> +const menu_open = ref(false)
https://github.com/utaipei-sa/reserve.utsa/pull/5/commits/a7fde8062e99df20f513ac81bb855ccebcf015b3

2024-06-28 07:52 UTC, Jeff92316046 commented on src/components/basic/DatePicker.vue
> +const date_temp = defineModel('date_temp')
https://github.com/utaipei-sa/reserve.utsa/pull/5/commits/a7fde8062e99df20f513ac81bb855ccebcf015b3

2024-06-28 07:53 UTC, Jeff92316046 commented
有一些垃圾命名可以再跟我講🤣

2024-06-28 08:10 UTC, nickchengtw commented on src/components/form/ItemDisplay.vue
> +          <v-row class="align-center" v-else>
為什麼需要用v-if顯示兩種不同版本的v-row?
能不能只用一個v-row配btn_flag控制按鈕的出現?

2024-06-28 08:10 UTC, nickchengtw commented on src/components/form/SpaceDisplay.vue
> +          <v-row v-else>
為什麼需要用v-if顯示兩種不同版本的v-row?
能不能只用一個v-row配btn_flag控制按鈕的出現?

2024-06-28 08:31 UTC, Jeff92316046 commented on src/components/form/ItemDisplay.vue
> +          <v-row class="align-center" v-else>
那個class裡面的東西不一樣
本來也是想用一個btn_flag去控制的
但那個布局會跑掉

2024-06-28 08:35 UTC, Jeff92316046 commented on src/components/form/ItemDisplay.vue
> +          <v-row class="align-center" v-else>
不然就是要額外再拉個component出來
或是用wh = useWindowSize()這個去判斷螢幕大小

2024-06-28 08:55 UTC, nickchengtw commented on src/components/form/ItemSelector.vue
> +    }, 5000)
這段跳出alert的程式在下面重複出現了
應該可以抽出變成function

2024-06-28 09:08 UTC, nickchengtw commented on src/components/form/SpaceSelector.vue
> +  format_temp1 += time_input.value.toString().split('-')[0]
46 47的值能不能直接用+合在一起然後改用const?

2024-06-28 09:09 UTC, nickchengtw commented on src/components/form/SpaceSelector.vue
> +  format_temp2 += time_input.value.toString().split('-')[1]
同上

2024-06-28 09:19 UTC, nickchengtw commented on src/components/form/SubmitDialog.vue
> +  for (var i = 0; i < submit_data.space_data.length; i++) {
改用foreach?

2024-06-28 09:19 UTC, nickchengtw commented on src/components/form/SubmitDialog.vue
> +  for (var i = 0; i < submit_data.item_data.length; i++) {
改用foreach?

2024-06-28 09:23 UTC, nickchengtw commented on src/components/form/SubmitDialog.vue
> +const addReserve = () => {
這個function的內容能不能直接搬到post_api裡面?

2024-06-28 09:27 UTC, Jeff92316046 commented on src/components/form/SubmitDialog.vue
> +const addReserve = () => {
addReserve應該是把那個dialog打開然後讓用戶確認資料，
dialog裡面還有一個按鈕是submit用的，這個才是post_api的

2024-06-28 09:30 UTC, Jeff92316046 commented on src/components/form/SubmitDialog.vue
> +  for (var i = 0; i < submit_data.item_data.length; i++) {
[https://tigercosmos.xyz/post/2021/06/js/js-array-for-methods/](https://tigercosmos.xyz/post/2021/06/js/js-array-for-methods/)
有必要嗎
不然就是全部的for迴圈都要改成foreach

2024-06-28 09:34 UTC, Jeff92316046 commented on src/components/form/SpaceSelector.vue
> +  format_temp1 += time_input.value.toString().split('-')[0]
這樣會比較好嗎
我自己不太喜歡在迴圈裡宣告const

2024-06-29 04:00 UTC, nickchengtw commented on src/components/form/SpaceSelector.vue
> +  format_temp1 += time_input.value.toString().split('-')[0]
如果它的值設計上是不可變的
用const可以防止它的值被改掉

2024-06-29 04:04 UTC, nickchengtw commented on src/components/form/SubmitDialog.vue
> +  for (var i = 0; i < submit_data.item_data.length; i++) {
如果在其他地方都是習慣用for迴圈那可以不用改
我覺得如果是要遍歷陣列foreach比較易讀

2024-06-29 04:10 UTC, nickchengtw commented on src/components/form/SubmitDialog.vue
> +const addReserve = () => {
用戶確認的資料是從submit_data裡讀取的
submit變數看起來只會被post_api使用到
所以我看因該能合在一起?

2024-06-29 09:12 UTC, Jeff92316046 commented on src/components/form/SubmitDialog.vue
> +const addReserve = () => {
add_reserve是綁第4行的dialog的button
post_api是綁第52行的button
不知道你有沒有試過form的繳交方式
它是兩段式的繳交
先用dialog去讓使用這預覽表單資料
確認之後再用dialog裡的button(第52行的button)去做繳交

2024-06-29 09:52 UTC, nickchengtw commented on src/components/form/SubmitDialog.vue
> +const addReserve = () => {
那就先維持原樣

2024-06-29 09:56 UTC, nickchengtw commented
我剛發現在表單新增場地後場地的刪除按鈕按了之後沒反應
物品的刪除按鈕是好的

2024-07-01 06:48 UTC, Jeff92316046 commented
這個應該有很多問題，可以討論一下
我也不知道怎麼寫比較好
我是參考這篇[https://ithelp.ithome.com.tw/articles/10263166](https://ithelp.ithome.com.tw/articles/10263166)
也有看一下請假系統的架構
如果要改的東西太多也可以再開個branch出去，感謝

2024-07-01 10:30 UTC, nickchengtw commented on .env
.env不能出現在git上
因為裡面還會用來放密碼之類的東西
.env裡需要的變數可能要寫在 .env.sample 檔案或是寫在文件裡

2024-07-01 10:34 UTC, Jeff92316046 commented on .env
行
我待會用.gitignore擋掉

2024-07-01 14:31 UTC, Jeff92316046 commented on .env
有需要用.env.development之類的東東嗎
[https://cn.vitejs.dev/guide/env-and-mode](https://cn.vitejs.dev/guide/env-and-mode)

2024-07-01 14:39 UTC, nickchengtw commented
> 這個應該有很多問題，可以討論一下 我也不知道怎麼寫比較好 我是參考這篇https://ithelp.ithome.com.tw/articles/10263166 也有看一下請假系統的架構 如果要改的東西太多也可以再開個branch出去，感謝

看起來沒什麼大問題
可以先用他的方法

2024-07-01 16:53 UTC, nickchengtw commented on .env
.env.development因該先不用
看來vite的設計是把.env.local忽略掉
我自己試.env.local的優先級比.env高
.env很像可以留著做預設值

2024-07-02 04:51 UTC, Jeff92316046 commented on .env
所以不用ignore了?

2024-07-02 04:54 UTC, nickchengtw commented on .env
因該可以不用
.env.local已經被ignore掉了
反正大原則就是敏感資訊不要出現在git上

2024-07-02 04:55 UTC, Jeff92316046 commented on .env
行

2024-07-10 06:16 UTC, Jeff92316046 commented
串接的部分再額外用就好，有些api還沒生出來所以也沒辦法測試

2024-07-12 04:19 UTC, nickchengtw approved these changes

2024-07-12 04:24 UTC, merged